const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{gracz: 0},
	{Solid: 0},
	{bariera2: 0},
	{bariera12: 0},
	{bariera22: 0},
	{bariera26: 0},
	{bariera27: 0},
	{bariera28: 0},
	{bariera29: 0},
	{bariera30: 0},
	{bariera31: 0},
	{bariera3: 0},
	{bariera4: 0},
	{bariera5: 0},
	{bariera6: 0},
	{bariera7: 0},
	{bariera8: 0},
	{bariera9: 0},
	{barira10: 0},
	{bariera1: 0},
	{bariera11: 0},
	{bariera13: 0},
	{bariera14: 0},
	{bariera15: 0},
	{bariera16: 0},
	{bariera17: 0},
	{bariera: 0},
	{bariera18: 0},
	{bariera19: 0},
	{bariera20: 0},
	{bariera21: 0},
	{bariera23: 0},
	{bariera24: 0},
	{bariera25: 0},
	{zbytek1: 0},
	{spawn: 0},
	{Platform: 0},
	{gracz2: 0},
	{platforma: 0},
	{artefakt1: 0},
	{detzone: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{BarbakanStart: 0},
	{zabytek2: 0},
	{TiledBackground4: 0},
	{gracz3: 0},
	{sciany2: 0},
	{ławkiKośćielne: 0},
	{ławkiKośćielne2: 0},
	{artefakt2: 0},
	{zabytek3: 0},
	{gracz4: 0},
	{sciany: 0},
	{LataLawa: 0},
	{artefakt3: 0},
	{TiledBackground5: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	gracz: class extends self.ISpriteInstance {},
	bariera2: class extends self.ISpriteInstance {},
	bariera12: class extends self.ISpriteInstance {},
	bariera22: class extends self.ISpriteInstance {},
	bariera26: class extends self.ISpriteInstance {},
	bariera27: class extends self.ISpriteInstance {},
	bariera28: class extends self.ISpriteInstance {},
	bariera29: class extends self.ISpriteInstance {},
	bariera30: class extends self.ISpriteInstance {},
	bariera31: class extends self.ISpriteInstance {},
	bariera3: class extends self.ISpriteInstance {},
	bariera4: class extends self.ISpriteInstance {},
	bariera5: class extends self.ISpriteInstance {},
	bariera6: class extends self.ISpriteInstance {},
	bariera7: class extends self.ISpriteInstance {},
	bariera8: class extends self.ISpriteInstance {},
	bariera9: class extends self.ISpriteInstance {},
	barira10: class extends self.ISpriteInstance {},
	bariera1: class extends self.ISpriteInstance {},
	bariera11: class extends self.ISpriteInstance {},
	bariera13: class extends self.ISpriteInstance {},
	bariera14: class extends self.ISpriteInstance {},
	bariera15: class extends self.ISpriteInstance {},
	bariera16: class extends self.ISpriteInstance {},
	bariera17: class extends self.ISpriteInstance {},
	bariera: class extends self.ISpriteInstance {},
	bariera18: class extends self.ISpriteInstance {},
	bariera19: class extends self.ISpriteInstance {},
	bariera20: class extends self.ISpriteInstance {},
	bariera21: class extends self.ISpriteInstance {},
	bariera23: class extends self.ISpriteInstance {},
	bariera24: class extends self.ISpriteInstance {},
	bariera25: class extends self.ISpriteInstance {},
	zbytek1: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	gracz2: class extends self.ISpriteInstance {},
	platforma: class extends self.ISpriteInstance {},
	artefakt1: class extends self.ISpriteInstance {},
	detzone: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	BarbakanStart: class extends self.ITextInstance {},
	zabytek2: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	gracz3: class extends self.ISpriteInstance {},
	sciany2: class extends self.ISpriteInstance {},
	ławkiKośćielne: class extends self.ISpriteInstance {},
	ławkiKośćielne2: class extends self.ISpriteInstance {},
	artefakt2: class extends self.ISpriteInstance {},
	zabytek3: class extends self.ISpriteInstance {},
	gracz4: class extends self.ISpriteInstance {},
	sciany: class extends self.ISpriteInstance {},
	LataLawa: class extends self.ISpriteInstance {},
	artefakt3: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {}
}